.code
  PUSH 60			contract SimpleStorage {\n    ...
  PUSH 40			contract SimpleStorage {\n    ...
  MSTORE 			contract SimpleStorage {\n    ...
  CALLVALUE 			contract SimpleStorage {\n    ...
  ISZERO 			contract SimpleStorage {\n    ...
  PUSH [tag] 1			contract SimpleStorage {\n    ...
  JUMPI 			contract SimpleStorage {\n    ...
  PUSH 0			contract SimpleStorage {\n    ...
  DUP1 			contract SimpleStorage {\n    ...
  REVERT 			contract SimpleStorage {\n    ...
tag 1			contract SimpleStorage {\n    ...
  JUMPDEST 			contract SimpleStorage {\n    ...
  PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract SimpleStorage {\n    ...
  DUP1 			contract SimpleStorage {\n    ...
  PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract SimpleStorage {\n    ...
  PUSH 0			contract SimpleStorage {\n    ...
  CODECOPY 			contract SimpleStorage {\n    ...
  PUSH 0			contract SimpleStorage {\n    ...
  RETURN 			contract SimpleStorage {\n    ...
.data
  0:
    .code
      PUSH 60			contract SimpleStorage {\n    ...
      PUSH 40			contract SimpleStorage {\n    ...
      MSTORE 			contract SimpleStorage {\n    ...
      PUSH 4			contract SimpleStorage {\n    ...
      CALLDATASIZE 			contract SimpleStorage {\n    ...
      LT 			contract SimpleStorage {\n    ...
      PUSH [tag] 1			contract SimpleStorage {\n    ...
      JUMPI 			contract SimpleStorage {\n    ...
      PUSH 0			contract SimpleStorage {\n    ...
      CALLDATALOAD 			contract SimpleStorage {\n    ...
      PUSH 100000000000000000000000000000000000000000000000000000000			contract SimpleStorage {\n    ...
      SWAP1 			contract SimpleStorage {\n    ...
      DIV 			contract SimpleStorage {\n    ...
      PUSH FFFFFFFF			contract SimpleStorage {\n    ...
      AND 			contract SimpleStorage {\n    ...
      DUP1 			contract SimpleStorage {\n    ...
      PUSH 60FE47B1			contract SimpleStorage {\n    ...
      EQ 			contract SimpleStorage {\n    ...
      PUSH [tag] 2			contract SimpleStorage {\n    ...
      JUMPI 			contract SimpleStorage {\n    ...
      DUP1 			contract SimpleStorage {\n    ...
      PUSH 6D4CE63C			contract SimpleStorage {\n    ...
      EQ 			contract SimpleStorage {\n    ...
      PUSH [tag] 3			contract SimpleStorage {\n    ...
      JUMPI 			contract SimpleStorage {\n    ...
    tag 1			contract SimpleStorage {\n    ...
      JUMPDEST 			contract SimpleStorage {\n    ...
      PUSH 0			contract SimpleStorage {\n    ...
      DUP1 			contract SimpleStorage {\n    ...
      REVERT 			contract SimpleStorage {\n    ...
    tag 2			function set(uint x) public {\...
      JUMPDEST 			function set(uint x) public {\...
      CALLVALUE 			function set(uint x) public {\...
      ISZERO 			function set(uint x) public {\...
      PUSH [tag] 4			function set(uint x) public {\...
      JUMPI 			function set(uint x) public {\...
      PUSH 0			function set(uint x) public {\...
      DUP1 			function set(uint x) public {\...
      REVERT 			function set(uint x) public {\...
    tag 4			function set(uint x) public {\...
      JUMPDEST 			function set(uint x) public {\...
      PUSH [tag] 5			function set(uint x) public {\...
      PUSH 4			function set(uint x) public {\...
      DUP1 			function set(uint x) public {\...
      DUP1 			function set(uint x) public {\...
      CALLDATALOAD 			function set(uint x) public {\...
      SWAP1 			function set(uint x) public {\...
      PUSH 20			function set(uint x) public {\...
      ADD 			function set(uint x) public {\...
      SWAP1 			function set(uint x) public {\...
      SWAP2 			function set(uint x) public {\...
      SWAP1 			function set(uint x) public {\...
      POP 			function set(uint x) public {\...
      POP 			function set(uint x) public {\...
      PUSH [tag] 6			function set(uint x) public {\...
      JUMP 			function set(uint x) public {\...
    tag 5			function set(uint x) public {\...
      JUMPDEST 			function set(uint x) public {\...
      STOP 			function set(uint x) public {\...
    tag 3			function get() public constant...
      JUMPDEST 			function get() public constant...
      CALLVALUE 			function get() public constant...
      ISZERO 			function get() public constant...
      PUSH [tag] 7			function get() public constant...
      JUMPI 			function get() public constant...
      PUSH 0			function get() public constant...
      DUP1 			function get() public constant...
      REVERT 			function get() public constant...
    tag 7			function get() public constant...
      JUMPDEST 			function get() public constant...
      PUSH [tag] 8			function get() public constant...
      PUSH [tag] 9			function get() public constant...
      JUMP 			function get() public constant...
    tag 8			function get() public constant...
      JUMPDEST 			function get() public constant...
      PUSH 40			function get() public constant...
      MLOAD 			function get() public constant...
      DUP1 			function get() public constant...
      DUP3 			function get() public constant...
      DUP2 			function get() public constant...
      MSTORE 			function get() public constant...
      PUSH 20			function get() public constant...
      ADD 			function get() public constant...
      SWAP2 			function get() public constant...
      POP 			function get() public constant...
      POP 			function get() public constant...
      PUSH 40			function get() public constant...
      MLOAD 			function get() public constant...
      DUP1 			function get() public constant...
      SWAP2 			function get() public constant...
      SUB 			function get() public constant...
      SWAP1 			function get() public constant...
      RETURN 			function get() public constant...
    tag 6			function set(uint x) public {\...
      JUMPDEST 			function set(uint x) public {\...
      DUP1 			x
      PUSH 0			storedData
      DUP2 			storedData = x
      SWAP1 			storedData = x
      SSTORE 			storedData = x
      POP 			storedData = x
      POP 			function set(uint x) public {\...
      JUMP [out]			function set(uint x) public {\...
    tag 9			function get() public constant...
      JUMPDEST 			function get() public constant...
      PUSH 0			uint
      DUP1 			storedData
      SLOAD 			storedData
      SWAP1 			return storedData
      POP 			return storedData
      SWAP1 			function get() public constant...
      JUMP [out]			function get() public constant...
    .data

